shdwmtr/simply-dark

Steam.css, TitleBar.css, headers/CompactHeader.css, overlay/Browser.css, overlay/GameNotes.css, overlay/GameOverview.css, overlay/Overlay.css, overlay/ScreenshotManager.css, skin.json, steam/TopBar.css, steam/friends/ChatWindow.css, steam/friends/FriendsList.css, steam/modal/ModalDialog.css, webkit/webkit.css
Multiple various fixes including
- Fixed transparency hover in topbar. 
- Fixed weird/unfinished chat styling. 
- Updated all outdated colors to match user input in millennium config skin.json. 
- Fixed dropdown background issue on Home.
=> Topbar Fix, Chat, and Colors

Steam.css, TitleBar.css, headers/NormalHeader.css, skin.json, webkit/webkit.css
Overlapping on hover with the steam no longer happens on minimal header.
Screenshots are styled on the game store page, alongside queue description positional fix.
Contrast issue when searching the store has been fixed as well.
A few other small issues patched as well.
=> Store Patches & Fixed Minimal Header

config/WalletVisibility.css, skin.json, steam/WalletVisibility.css
Updated Hide Wallet feature to match the beta classes.
=> Updated Hide Wallet

webkit/webkit.css
=> Fixed Inventory Page

Steam.css, colors.css, headers/CompactHeader.css, headers/NormalHeader.css, overlay/Browser.css, overlay/ScreenshotManager.css, skin.json, steam/DownloadsPage.css, steam/Properties.css, steam/friends/FriendsList.css, steam/modal/ModalDialog.css, webkit/webkit.css
- replaces most hardcoded color values with variables found in color settings
- adds `--brightblue` color variable
=> use variables from color settings

webkit/webkit.css
- Matched top profile's width section with bottom profile's width section
- Changed rounded border radius on top profile section
- Added top padding on bottom section
- Added rounded border on bottom section
**Visual comparison:**
a. Current build
b. Proposed changes
=> Changed Profile Page

TitleBar.css
Fixed (hopefully) the "View" and "Games" bar on the top left menu
=> Fix the "View" and "Games" bar

skin.json, webkit/modules/other_module.js, webkit/store.js
Added cross compatibility configuration on _skin.json_ for millennium beta and public branch
=> 1.3.0: skin.json new format

Steam.css, colors.css, webkit/reservedWebkitColors.css
- Adjusting the colors format compatibility for Millennium Beta
_Totally unrelated note:_ The color names are placeholder, if you want to fix these _Totally-Not-Ambiguous™_ color names, feel free to make a pull request.
=> 1.3.0.1: New colors settings format

webkit/webkit.css
- Fixed the "guide" page theming to align with Simply Dark's colors. (#28)
=> 1.3.0.3: Fixed guide page theming

webkit/webkit.css
- Fixed the steam points page theming to align with Simply Dark's colors. (#26)
=> 1.3.1.1: Fixed steam points page theming

Steam.css
- Notification button will turn into green whenever there's a notification available.
=> 1.3.1.2: Updated notification button

headers/CompactHeader.js, headers/NormalHeader.js
- Hopefully fixed the delayed top right icons position adjustment when opening steam for the first time.
=> 1.3.1.3: Fixed top right icons timing

README.md, Steam.css, skin.json, steam/friends/FriendsList.css
- Fixed various context and pop up menu colors
- Fixed settings page color
=> 1.3.2: Steam Family Beta update

Steam.css, config/AvatarFrames.css, config/FriendsOutline.css, steam/friends/FriendsList.css
- Fixed various issues with friend list tab
=> 1.3.2.1: Friendlist fix

Steam.css
- Fixed various broken context menu colors
=> 1.3.2.2: Fixed context menus colors

Steam.css
- Disabled the rounded border for context menus
=> 1.3.2.2b: Fixed the rounded border

Steam.css
- Fixed few things related to color on settings page
=> 1.3.2.3: Fixed few settings colors

steam/friends/ChatWindow.css, steam/friends/FriendsList.css
- Fixed various colors issue related to steam chat window
=> 1.3.2.4: Fixed steam chat colors

Steam.css
- Fixed collection background colors.
=> 1.3.2.5: Fixed Collection Colors

Steam.css
- Fixed soundtrack background color to dark
=> 1.3.2.6: Fixed soundtrack background colors

Steam.css
- Fixed game recording selectable container color
=> 1.3.3: Game Recording Update

webkit/webkit.css
Replaced hardcoded `border-radius` in profile buttons with the `--border0` variable to ensure a consistent appearance with other buttons.
=> 1.3.3.2: `--border0` for profile buttons

Steam.css, webkit/webkit.css
Added classes for subscribed modes (#58) and for the family manage
<details><summary>Screenshots</summary>
</details>
=> Subscribed modes and family manage classes fix

TitleBar.css
- Fixed the small icon on the window when clicking game update (#61)
=> 1.3.3.5: Fixed small "x" icon on some window

TitleBar.css
- Fixed close button size on achievement window
=> 1.3.3.6: Fixed x icon on achievement window

Steam.css
- Fixed right click context menus colors (thanks God)
=> 1.3.4: Fixed Context Menus Colors

steam/Properties.css
=> 1.3.4.4: Fixed Setting Confirmation Buttons

webkit/webkit.css
- Fixed workshop description on profile showcase
=> 1.3.4.5: Fixed Workshop Description

Steam.css
- Fixed family view button on the top right
=> 1.3.4.6: Family View Fix

skin.json, webkit/webkit.css
- Changed new store navbar color to dark (It's called simple **dark** for a reason)
=> 1.4: Fixed Some of New Store Theming
